name: ItemExchange
main: com.github.arowshot.itemexchange.ItemExchangePlugin
version: ${releaseVersion}
author: ArowShot
depend: [CivModCore]
softdepend: [Mercury]
description: need to write this
commands:
  iec:
    aliases: [iecreate, iecreate]
  iem:
    aliases: [iemodify]
permissions:
  itemexchange.admin:
    deafult: op